name = "Search Emojis"
description = "Search through emojis and paste them to current applciation"
endpointURL = "https://slapcommands.vercel.app/api/utils/emoji-paster"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/utils/emoji-paster.js"
language = "javascript"
categories = ["Utilities"]
author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
The command allows you searching through emojis and pasting them to the current applciation.

It is also available as a [Local Command](https://github.com/AnishDe12020/slapcommands).
"""

