name = "Hacker News Front Page"
description = "Scan through the Hacker News front page and jump to posts or comments."
endpointURL = "https://www.taraszubyk.com/api/slapdash/hn-front-page"
sourceCodeURL = "https://github.com/zuta/slapdash-commands/blob/master/api/slapdash/hn-front-page.ts"

language = "typescript"
categories = ["News"]

author.name = "Taras Zubyk"
author.profileURL = "https://twitter.com/_zuta_/"

readme = """
This command uses the [RSS Feed](https://hnrss.org/frontpage) of the [Hacker News](https://news.ycombinator.com/) front page to let you quickly scan 
through the latest posts. 

Each option in the list displays the post's title, information about the author and some insights e.g. the number of comments that were made on Hacker News.
You can choose to jump directly to the post or the comments section on Hacker News.
"""