name = "Search Chakra UI Docs"
description = "Search through Chakra UI documentation"
endpointURL = "https://slapcommands.vercel.app/api/docsearch/chakra-ui"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/docsearch/chakra-ui-docs.js"
language = "javascript"
categories = ["Developer Tools", "Productivity", "Documentation"]

author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
This command lets you search through the [Chakra UI documentation](https://chakra-ui.com/guides/first-steps) and open it
up on your browser. You can also copy the URL to the documentation and also
paste the URL to the documentation to your current application.

It is also available as a local command, details here - https://github.com/AnishDe12020/slapcommands
"""
