name = "Show Current UNIX Timestamp"
description = "Quickly see or copy the current UNIX timestamp"
endpointURL = "https://slapcommands.vercel.app/api/utils/unix-timestamp"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/utils/unix-timestamp.js"
language = "javascript"
categories = ["Developer Tools", "Productivity", "Utilities"]

author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
This command shows the current UNIX timestamp and lets you copy it to the clipboard.

The command is also available as a [Local Command](https://github.com/AnishDe12020/slapcommands).
"""

