name = "Parse User-Agent"
description = "Parse a User-Agent string by pasting it into the Command Bar."
endpointURL = "https://www.taraszubyk.com/api/slapdash/parse-user-agent"

author.name = "Taras Zubyk"
author.profileURL = "https://twitter.com/_zuta_"