name = "Search Slapdash Platform Docs"
description = "Search through Slapdash Platform documentation"
endpointURL = "https://slapcommands.vercel.app/api/docsearch/slapdash-platform"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/docsearch/slapdash-platform-docs.js"
language = "javascript"
categories = ["Developer Tools", "Documentation"]

author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
The command lets you search through the [Slapdash Platform documentation](https://platform.slapdash.com/). You can copy the URL to the individual pages or paste it to the current application.

It is also available as a [Local Command](https://github.com/AnishDe12020/slapcommands).
"""
